version: '3.7'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/book_explorer
    ports:
      - 8000:8000
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      AWS_ACCESS_KEY_ID: add_yours
      AWS_SECRET_ACCESS_KEY: add_yours
    depends_on:
      - redis
  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery --app book_explorer  worker -l info
    volumes:
      - .:/book_explorer
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      AWS_ACCESS_KEY_ID: add_yours
      AWS_SECRET_ACCESS_KEY: add_yours
    depends_on:
      - web
      - redis
  flower:
    image: mher/flower
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    ports:
      - 5555:5555
    depends_on:
      - redis
