# Generated by Django 4.1.7 on 2023-03-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=100)),
                ("s3_url", models.URLField()),
                ("date_uploaded", models.DateTimeField(verbose_name="date uploaded")),
                ("md5_checksum", models.CharField(max_length=50)),
            ],
        ),
    ]
